---
title: "IZV-515 VERi GöRSELLEŞTİRME VE İŞ RAPORLAMA"
author: "Ahmet ÇETİNKAYA-6006049"
date: "06/12/2020"
output:
  html_document:
    df_print: paged 
  word_document: default 
  pdf_document: default
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


```{r  covid-19 Turkiye Kasim 2020, echo=FALSE, message=FALSE, warning=FALSE, fig.align = 'center',fig.height=50.0, fig.width=50.0}

library(readr)
library(ggplot2)
library(dplyr)
library(hrbrthemes)
library(readxl)
library(lubridate)
library(cowplot)
library(ggpubr)

covidVeri <- read_csv("https://covid.ourworldindata.org/data/owid-covid-data.csv")

covidVeriTurkiye <- filter(covidVeri, location == "Turkey")

covid_kasim <- filter(covidVeriTurkiye, date >= "2020-11-15" & date <= "2020-11-30")



# Toplam vaka sayisi

p_tv <- ggplot(covid_kasim, aes(date, total_cases)) +
  geom_col(fill= "red") +
  scale_x_date(date_labels =  "%d-%m", date_breaks = "1 day") +
  scale_y_continuous(labels = scales::comma) +
  coord_cartesian(ylim = c(350000, 700000)) +
  labs(x = "Tarih", y = "Toplam Vaka", 
       title = "Kasım 2020 COVID-19 Toplam Vaka Sayısı",
       subtitle = "15.11.2020-30.11.2020 tarihleri arası COVID-19 toplam vaka sayısı",
       caption = "Kaynak: https://ourworldindata.org/coronavirus-testing") + 
  theme_minimal_grid() +
  theme(axis.text = element_text(size = 50),
        axis.title = element_text(size = 50),
    plot.title = element_text(color = "red", size = 50, face = "bold"),
    plot.subtitle = element_text(color = "blue", size = 40),
    plot.caption = element_text(color = "brown", size = 30, face = "italic")) + 
  theme(axis.text.x=element_text(angle=90, hjust=1)) 

# Toplam Ölüm Sayisi
p_to <- ggplot(covid_kasim, aes(date, total_deaths)) + 
  geom_col(fill= "darkred") +
  scale_x_date(date_labels =  "%d-%m", date_breaks = "1 day") +
  scale_y_continuous(labels = scales::comma)+
  coord_cartesian(ylim = c(10000, 14500))+
  labs(x = "Tarih", y = "Toplam Ölüm", 
       title = "Kasım 2020 COVID-19 Toplam Ölüm Sayısı",
       subtitle = "15.11.2020-30.11.2020 tarihleri arası COVID-19 toplam ölüm sayısı",
       caption = "Kaynak: https://ourworldindata.org/coronavirus-testing") + 
  theme_minimal_grid() +
  theme(axis.text = element_text(size = 50),
        axis.title = element_text(size = 50),
    plot.title = element_text(color = "red", size = 50, face = "bold"),
    plot.subtitle = element_text(color = "blue", size = 40),
    plot.caption = element_text(color = "brown", size = 30, face = "italic")) + 
  theme(axis.text.x=element_text(angle=90, hjust=1)) 

# Günlük Vaka Sayisi
p_gv <- ggplot(covid_kasim, aes(date, new_cases)) + 
  geom_col(fill = "lightblue") +
  scale_x_date(date_labels =  "%d-%m", date_breaks = "1 day") +
  scale_y_continuous(labels = scales::comma) +
  labs(x = "Tarih", y = "Günlük Vaka", 
       title = "Kasım 2020 COVID-19 Günlük Vaka Sayısı",
       subtitle = "15.11.2020-30.11.2020 tarihleri arası COVID-19 günlük vaka sayısı",
       caption = "Kaynak: https://ourworldindata.org/coronavirus-testing")+
  theme_minimal_grid() +
  theme(axis.text = element_text(size = 50),
        axis.title = element_text(size = 50),
    plot.title = element_text(color = "red", size = 50, face = "bold"),
    plot.subtitle = element_text(color = "blue", size = 40),
    plot.caption = element_text(color = "brown", size = 30, face = "italic")) +
  theme(axis.text.x=element_text(angle=90, hjust=1)) 

# Günlük Ölüm Sayisi
p_go <- ggplot(covid_kasim, aes(date, new_deaths)) + 
  geom_col(fill = "blue") +
  geom_text(mapping = aes(label = new_deaths, new_deaths = new_deaths + 0.05), position = position_dodge(0.9), vjust = 0, size = 15,color="red")+
  scale_x_date(date_labels =  "%d-%m", date_breaks = "1 day") +
  scale_y_continuous(labels = scales::comma) +
  labs(x = "Tarih", y = "Günlük Ölüm", 
       title = "Kasım 2020 COVID-19 Günlük Ölüm Sayısı",
       subtitle = "15.11.2020-30.11.2020 tarihleri arası COVID-19 günlük ölüm sayısı",
       caption = "Kaynak: https://ourworldindata.org/coronavirus-testing")+
  theme_minimal_grid() +
  theme(axis.text = element_text(size = 50),
        axis.title = element_text(size = 50),
    plot.title = element_text(color = "red", size = 50, face = "bold"),
    plot.subtitle = element_text(color = "blue", size = 40),
    plot.caption = element_text(color = "brown", size = 30, face = "italic")) +
  theme(axis.text.x=element_text(angle=90, hjust=1)) 

#vaka ve ölümler
df_toplam_vaka <- data.frame(covid_kasim$date, covid_kasim$total_cases)

df_toplam_olum <- data.frame(covid_kasim$date, covid_kasim$total_deaths)

df_gunluk_vaka <- data.frame(covid_kasim$date, covid_kasim$new_cases)

df_gunluk_olum <- data.frame(covid_kasim$date, covid_kasim$new_deaths)

df_tum_veriler <- data.frame(covid_kasim$date, covid_kasim$total_cases, covid_kasim$total_deaths, covid_kasim$new_cases, covid_kasim$new_deaths)

#column adlarını değiştir
colnames(df_tum_veriler)[] <- c('Tarih', 'Toplam vaka', 'Toplam Ölüm', 'Günlük Vaka', 'Günlük Ölüm')

#verilere göre tek tablo yap
melt_vakalari <- reshape2::melt(df_tum_veriler, id.var = "Tarih")


#line olarak göster
p_gtl <- ggplot(melt_vakalari, aes(x = Tarih, y = value, group = variable, col = variable)) +
  geom_line(size=5) +
  scale_x_date(date_labels =  "%d-%m", date_breaks = "1 day") +
  scale_y_continuous(name = "Vaka Sayıları", labels = scales::comma) + 
  labs(x = "Tarih",  
     title = "Kasım 2020 COVID-19 Tablosu",
     subtitle = "15.11.2020-30.11.2020 tarihleri arası COVID-19 verisi",
     caption = "Kaynak: https://ourworldindata.org/coronavirus-testing")+
  theme_minimal_grid() +
  theme(axis.text = element_text(size = 50),
        axis.title = element_text(size = 50),
    plot.title = element_text(color = "red", size = 50, face = "bold"),
    plot.subtitle = element_text(color = "blue",size = 40),
    plot.caption = element_text(color = "gray", size =30, face = "italic"),
    legend.title = element_text(size = 40),
    legend.text = element_text(size = 30)) + 
  theme(axis.text.x=element_text(angle=90, hjust=1)) 

#logaritmik olarak göster
p_gtlog <- ggplot(melt_vakalari, aes(x = Tarih, y = value, group = variable, col = variable)) +
  geom_line(size=5) +
  scale_x_date(date_labels =  "%d-%m", date_breaks = "1 day") +
  scale_y_log10(name = "Vaka Sayıları (Logaritmik)", labels = scales::comma) + 
  labs(x = "Tarih",  
     title = "Kasım 2020 COVID-19 Tablosu",
     subtitle = "15.11.2020-30.11.2020 tarihleri arası COVID-19 verisi",
     caption = "Kaynak: https://ourworldindata.org/coronavirus-testing")+
  theme_minimal_grid() +
  theme(axis.text = element_text(size = 50),
        axis.title = element_text(size = 50),
    plot.title = element_text(color = "red", size = 50, face = "bold"),
    plot.subtitle = element_text(color = "blue",size = 40),
    plot.caption = element_text(color = "gray", size =30, face = "italic"),
    legend.title = element_text(size = 40),
    legend.text = element_text(size = 30)) + 
  theme(axis.text.x=element_text(angle=90, hjust=1)) 


# tüm tabloları tek olarak hazırla   plot_grid(p_gt, p_tab,...)
plot_grid(p_gtl,p_gtlog,p_tv, p_to, p_gv, p_go, nrow = 3, ncol = 2, align = "hv", margin(20,20,20,20))


```
