---
title: "Odev-2"
author: "Ahmet ÇETİNKAYA"
date: "03/12/2020"
output:
  word_document: default
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(
 fig.width = 6,
 fig.asp = 0.8,
 out.width = "30%"
)
```

---
title: 15.Kasım.2020-30.Kasım.2020 COVID-19 Verileri
---
```{r covid-19 Türkiye Kasım 2020, echo=FALSE, message=FALSE, warning=FALSE}
install.packages('hrbrthemes')
install.packages("lubridate")
install.packages("digest")
library(readr)
library(ggplot2)
library(dplyr)
library(hrbrthemes)

covidVeri <- read_csv("https://covid.ourworldindata.org/data/owid-covid-data.csv")
View(covidVeri)
covidVeriTurkiye <- filter(covidVeri, location == "Turkey")
View(covidVeriTurkiye)
covid_kasim <- filter(covidVeriTurkiye, date >= "2020-11-15" & date <= "2020-11-30")
View(covid_kasim)




ggplot(covidVeri, aes(covidVeri$date, covidVeri$total_cases)) + 
  geom_col(fill= "#6A1B9A") +
  scale_y_continuous(labels = scales::comma) +
  labs(x = "Tarih", y = "Toplam Vaka", 
       title = "Kasım 2020 COVID Toplam Vaka Sayısı",
       subtitle = "15.11.2020-30.11.2020 tarihleri arası COVID-19 vaka sayısı",
       caption = "Veri: https://ourworldindata.org/coronavirus-testing")+
  theme_classic()


ggplot(covidVeri, aes(covidVeri$date, covidVeri$total_deaths)) + 
  geom_col(fill= "#AB47BC") +
  scale_y_continuous(labels = scales::comma) + 
  labs(x = "Tarih", y = "Toplam Ölüm", 
       title = "Kasım 2020 COVID Toplam Ölüm Sayısı",
       subtitle = "15.11.2020-30.11.2020 tarihleri arası COVID-19 ölüm sayısı",
       caption = "Veri: https://ourworldindata.org/coronavirus-testing")+
  theme_classic()
  

ggplot(covidVeri, aes(covidVeri$date, covidVeri$new_cases)) + 
  geom_col(fill= "orange") +
  scale_y_continuous(labels = scales::comma) +
  labs(x = "Tarih", y = "Günlük Vaka", title = "Kasım 2020 COVID Günlük Vaka Sayısı",
       subtitle = "15.11.2020-30.11.2020 tarihleri arası COVID-19 ölüm sayısı",
       caption = "Veri: https://ourworldindata.org/coronavirus-testing")+
  theme_classic()
  
  


ggplot(covidVeri, aes(covidVeri$date, covidVeri$new_deaths)) + 
  geom_col(fill= "#F44336") +
  scale_y_continuous(labels = scales::comma) +
  labs(x = "Tarih", y = "Günlük Ölüm", title = "Kasım 2020 COVID Günlük Ölüm Sayısı",
       subtitle = "15.11.2020-30.11.2020 tarihleri arası COVID-19 ölüm sayısı",
       caption = "Veri: https://ourworldindata.org/coronavirus-testing")+
  theme_classic()


#vaka ve ölümler
df_gunluk_vaka <- data.frame(covidVeri$date, covidVeri$gunluk_vaka)

df_gunluk_olum <- data.frame(covidVeri$date, covidVeri$gunluk_olum)

df_toplam_vaka <- data.frame(covidVeri$date, covidVeri$toplam_vaka)

df_toplam_olum <- data.frame(covidVeri$date, covidVeri$toplam_olum)

df_tum_veriler <- data.frame(covidVeri$date, covidVeri$toplam_vaka, covidVeri$toplam_olum, covidVeri$gunluk_vaka, covidVeri$gunluk_olum)

melt_vakalari <- reshape2::melt(df_tum_veriler, id.var = "covidVeri.tarih")


ggplot(melt_vakalari, aes(x = covidVeri.tarih, y = value, group = variable, col = variable)) +
  geom_line() +
  scale_y_log10(name = "Vaka Sayıları", labels = scales::comma) +
  labs(x = "Tarih", y = "Değerler", title = "Kasım 2020 COVID Günlük Ölüm Sayısı",
       subtitle = "15.11.2020-30.11.2020 tarihleri arası COVID-19 logaritmik değişimi",
       caption = "Veri: https://ourworldindata.org/coronavirus-testing")+
  theme_classic()




```

